
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "GENDER ID_AREAS ID_CONCEPT ID_COUNTRY ID_LANG ID_LANGS SEP SEP2 SEP3 TYPE_TERM WORDSdic : conceptsconcepts : concept conceptsconcepts : conceptconcept : ID_CONCEPT '.' SEP areas SEP langsareas : ID_AREAS name_areasname_areas : SEP '-' WORDS name_areasname_areas : SEP '-' WORDSlangs : ID_LANGS type_langtype_lang : SEP '*' ID_LANG termsterms : SEP2 '-' WORDS qual_term var_country termsterms : SEP2 '-' WORDS qual_term var_countryterms : SEP2 '-' WORDS qual_term termsterms : SEP2 '-' WORDS qual_termterms : SEP2 '-' WORDS var_country termsterms : SEP2 '-' WORDS var_countryterms : SEP2 '-' WORDS termsterms : SEP2 '-' WORDSqual_term : '(' GENDER '|' TYPE_TERM ')'qual_term : '(' GENDER ')'var_country : SEP3 '+' ID_COUNTRY"
    
_lr_action_items = {'ID_CONCEPT':([0,3,13,16,22,25,26,27,28,31,32,33,36,38,39,41,],[4,4,-4,-8,-9,-17,-13,-15,-16,-11,-12,-14,-10,-19,-20,-18,]),'$end':([1,2,3,5,13,16,22,25,26,27,28,31,32,33,36,38,39,41,],[0,-1,-3,-2,-4,-8,-9,-17,-13,-15,-16,-11,-12,-14,-10,-19,-20,-18,]),'.':([4,],[6,]),'SEP':([6,8,9,11,14,18,20,],[7,10,12,-5,17,12,-6,]),'ID_AREAS':([7,],[9,]),'ID_LANGS':([10,],[14,]),'-':([12,23,],[15,24,]),'WORDS':([15,24,],[18,25,]),'*':([17,],[19,]),'ID_LANG':([19,],[21,]),'SEP2':([21,25,26,27,31,38,39,41,],[23,23,23,23,23,-19,-20,-18,]),'(':([25,],[29,]),'SEP3':([25,26,38,41,],[30,30,-19,-18,]),'GENDER':([29,],[34,]),'+':([30,],[35,]),'|':([34,],[37,]),')':([34,40,],[38,41,]),'ID_COUNTRY':([35,],[39,]),'TYPE_TERM':([37,],[40,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dic':([0,],[1,]),'concepts':([0,3,],[2,5,]),'concept':([0,3,],[3,3,]),'areas':([7,],[8,]),'name_areas':([9,18,],[11,20,]),'langs':([10,],[13,]),'type_lang':([14,],[16,]),'terms':([21,25,26,27,31,],[22,28,32,33,36,]),'qual_term':([25,],[26,]),'var_country':([25,26,],[27,31,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dic","S'",1,None,None,None),
  ('dic -> concepts','dic',1,'p_dic','parser.py',6),
  ('concepts -> concept concepts','concepts',2,'p_concepts','parser.py',10),
  ('concepts -> concept','concepts',1,'p_concepts_single','parser.py',14),
  ('concept -> ID_CONCEPT . SEP areas SEP langs','concept',6,'p_concept','parser.py',18),
  ('areas -> ID_AREAS name_areas','areas',2,'p_areas','parser.py',22),
  ('name_areas -> SEP - WORDS name_areas','name_areas',4,'p_name_areas','parser.py',26),
  ('name_areas -> SEP - WORDS','name_areas',3,'p_name_areas_single','parser.py',30),
  ('langs -> ID_LANGS type_lang','langs',2,'p_langs','parser.py',34),
  ('type_lang -> SEP * ID_LANG terms','type_lang',4,'p_type_lang','parser.py',38),
  ('terms -> SEP2 - WORDS qual_term var_country terms','terms',6,'p_terms','parser.py',42),
  ('terms -> SEP2 - WORDS qual_term var_country','terms',5,'p_terms_single','parser.py',46),
  ('terms -> SEP2 - WORDS qual_term terms','terms',5,'p_terms_only_qual','parser.py',50),
  ('terms -> SEP2 - WORDS qual_term','terms',4,'p_terms_only_qual_single','parser.py',54),
  ('terms -> SEP2 - WORDS var_country terms','terms',5,'p_terms_only_var','parser.py',58),
  ('terms -> SEP2 - WORDS var_country','terms',4,'p_terms_only_var_single','parser.py',62),
  ('terms -> SEP2 - WORDS terms','terms',4,'p_terms_simple','parser.py',66),
  ('terms -> SEP2 - WORDS','terms',3,'p_terms_simple_single','parser.py',70),
  ('qual_term -> ( GENDER | TYPE_TERM )','qual_term',5,'p_qual_term','parser.py',74),
  ('qual_term -> ( GENDER )','qual_term',3,'p_qual_term_only_gender','parser.py',78),
  ('var_country -> SEP3 + ID_COUNTRY','var_country',3,'p_var_country','parser.py',82),
]
